### ISSUE TITLE
RangeError: Source is too large in opus.js

### ISSUE THREAD

**Issue by airdrummingfool** [geekuillaume/soundsync#17]
Hello,
I just downloaded soundsync to play around on my 2012 Macbook Pro and 2012 Mac mini. I opened the app on the mini first, and linked the `Built-in Input` to the `Built-in Output`. Then I opened the app on my MBP and linked the mini's `Built-in Input` to the MBP's `Built-in Output` (so the mini's input was going to both the mini and the MBP's output).

soundsync on the mini almost immediately crashed with the following error message:
```
RangeError: Source is too large
    at Uint8Array.set (<anonymous>)
    at OpusEncoder.encodeFloat (/Applications/Soundsync.app/Contents/Resources/app/utils/opus.js:104:18)
    at /Applications/Soundsync.app/Contents/Resources/app/utils/opus_streams.js:18:38
```

Since then, any time I try to start the app on my mini it crashes immediately with the same error.

On the MBP, It has crashed without an app error (just the generic Apple 'report error' screen) a couple times, but it will still launch and doesn't crash right away (though testing playing audio with Spotify did crash with a different error).

I'm excited to see where this project goes!

**Comment by geekuillaume** [comment]
I encountered this error yesterday night just when friends arrived at my home, didn't had time to debug it so I switched to Spotify on a single speaker (eating my own dog food 😅). I made a change to the audio resampler yesterday and didn't test it enough. I just pushed a new update with the fix. It has the same version number. Can you try again?

I'm going to separate the relatively stable version from the bleeding edge dev version soon to prevent this kind of errors.

**Comment by airdrummingfool** [comment]
I just tried the new build, and it still crashes. The first time I launched it the error was the same, but the second time the error was a bit different:
```
Error: invalid argument
    at OpusEncoder.encodeFloat (/Applications/Soundsync.app/Contents/Resources/app/utils/audio/opus.js:108:19)
    at /Applications/Soundsync.app/Contents/Resources/app/utils/audio/opus_streams.js:18:38
```

Subsequent launches all crash and show the original `Source is too large` error. There's also some relatively loud, momentary popping/glitch-type noises from my speakers each time it launches.

**Comment by geekuillaume** [comment]
@airdrummingfool I've changed a lot of things recently and I can't reproduce your error. Can you try again with the last version (v0.2.4)?

**Comment by airdrummingfool** [comment]
This appears to be fixed in 0.2.4. Thanks!

**Comment by airdrummingfool** [comment]
I take that back - 10 seconds after I closed this issue, it happened again lol. I was trying to link the Built-in Input of the mini to the Built-in Output of the 2012 MacBook Pro, and the app crashed with the range error on the mini.

**Comment by geekuillaume** [comment]
@airdrummingfool I've managed to reproduce the error on my setup and found the problem. Can you test with the latest dev build? If this still happens, feel free to reopen this issue.

**Comment by airdrummingfool** [comment]
@geekuillaume Will do, but I'm a bit confused on where to get the latest dev build - v0.2.4 doesn't include the fix, and the releases from the (Bleeding Edge tag)[https://github.com/geekuillaume/soundsync/releases/tag/bleeding-edge] seems to not have been updated since July 21st. Can you point me in the right direction?

**Comment by geekuillaume** [comment]
@airdrummingfool The bleeding edge tag isn't updated automatically but is used to host the last build from Github actions. For macOS, the last build is "soundsync-0.2.4.dmg". I need to improve the naming for sure!

**Comment by airdrummingfool** [comment]
Ah, gotcha. That's definitely confusing - the [`0.2.4` tag](https://github.com/geekuillaume/soundsync/releases/tag/v0.2.4) has a different `soundsync-0.2.4.dmg` file than the [`Bleeding edge` tag](https://github.com/geekuillaume/soundsync/releases/tag/bleeding-edge).

The new build has changed things a bit; the app no longer crashes with the error message listed in the issue title. However, the app still crashes - seemingly at random now. I'll keep playing around, and if it continues to happen I'll open a new issue. Thanks!
