### ISSUE TITLE
Trying to get things up and running

### ISSUE THREAD

**Issue by dustinkerstein** [geekuillaume/soundsync#3]
Hey! Very intrigued by your project, and I may have business use for it. But I wanted to get it running on home first. I tried setting up the server on my Windows 10 machine with the input being the Stereo Mix (alternative to Loopback for some soundcards). Sometimes I'm able to get the connection hooked up, but other times I just get an infinite spinner on the root page that says "Connecting..."  The only server-side debug I see in the browser is:

```
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a3ad7e5d_8006_4024_9994_382a5e4d92f3-10-98-10-6.sslip.io:6513/. (Reason: CORS request did not succeed).
```

On my Macbook Pro, I tried setting up the server and it launches. When I tried hooking up the microphone input, it crashes the server app almost immediately. When it stays open long enough to open the browser page I see this in the debug:

```
main-da815c25abb660aaed43.js:103 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
_startSink @ main-da815c25abb660aaed43.js:103
main-da815c25abb660aaed43.js:103 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
_startSink @ main-da815c25abb660aaed43.js:103
f60e6d23_541c_42d8_b464_198c26c0c930-192-168-239-1.sslip.io:6513/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
2a94c278e_7c41_43ee_82ac_aaed159d2493-10-0-1-147.sslip.io:6513/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
f60e6d23_541c_42d8_b464_198c26c0c930-192-168-239-1.sslip.io:6513/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
a94c278e_7c41_43ee_82ac_aaed159d2493-10-0-1-147.sslip.io:6513/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
f60e6d23_541c_42d8_b464_198c26c0c930-192-168-239-1.sslip.io:6513/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
315468647_cf3a_4cf2_a228_697b3d7c2310-172-16-107-1.sslip.io:6513/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
5:6512/initiator/aa036a0f-9533-435b-a60e-9676d51712da/messages:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
3main-da815c25abb660aaed43.js:103 GET http://localhost:6512/initiator/aa036a0f-9533-435b-a60e-9676d51712da/messages net::ERR_CONNECTION_REFUSED
(anonymous) @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
f._end @ main-da815c25abb660aaed43.js:21
f.end @ main-da815c25abb660aaed43.js:21
(anonymous) @ main-da815c25abb660aaed43.js:88
r.then @ main-da815c25abb660aaed43.js:88
main-da815c25abb660aaed43.js:103 POST http://localhost:6512/initiator/aa036a0f-9533-435b-a60e-9676d51712da/messages net::ERR_CONNECTION_REFUSED
(anonymous) @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
f._end @ main-da815c25abb660aaed43.js:21
f.end @ main-da815c25abb660aaed43.js:21
(anonymous) @ main-da815c25abb660aaed43.js:88
r.then @ main-da815c25abb660aaed43.js:88
setTimeout (async)
(anonymous) @ main-da815c25abb660aaed43.js:103
connect @ main-da815c25abb660aaed43.js:103
async function (async)
connect @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
n @ main-da815c25abb660aaed43.js:103
main-da815c25abb660aaed43.js:103 GET http://localhost:6512/initiator/aa036a0f-9533-435b-a60e-9676d51712da/messages net::ERR_CONNECTION_REFUSED
(anonymous) @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
f._end @ main-da815c25abb660aaed43.js:21
f.end @ main-da815c25abb660aaed43.js:21
(anonymous) @ main-da815c25abb660aaed43.js:88
r.then @ main-da815c25abb660aaed43.js:88
main-da815c25abb660aaed43.js:103 POST http://localhost:6512/initiator/aa036a0f-9533-435b-a60e-9676d51712da/messages net::ERR_CONNECTION_REFUSED
```

When trying to connect from my Macbook via Chrome to the Windows server I see the audio connection to the browser, but I get no audio. Here's the debug:

```
main-da815c25abb660aaed43.js:103 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
_startSink @ main-da815c25abb660aaed43.js:103
_syncPipeState @ main-da815c25abb660aaed43.js:21
async function (async)
_syncPipeState @ main-da815c25abb660aaed43.js:21
a.emit @ main-da815c25abb660aaed43.js:1
addSource @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
On.handlePeerSoundStateUpdate @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
a.emit @ main-da815c25abb660aaed43.js:1
C._onReceivedMessage @ main-da815c25abb660aaed43.js:1
handleControllerMessage @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
n @ main-da815c25abb660aaed43.js:103
10.0.1.10/:1 Access to XMLHttpRequest at 'https://soundsync.app/api/ip_registry/peers' from origin 'http://10.0.1.10:6512' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main-da815c25abb660aaed43.js:103 GET https://soundsync.app/api/ip_registry/peers net::ERR_FAILED
(anonymous) @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
f._end @ main-da815c25abb660aaed43.js:21
f.end @ main-da815c25abb660aaed43.js:21
(anonymous) @ main-da815c25abb660aaed43.js:88
r.then @ main-da815c25abb660aaed43.js:88
main-da815c25abb660aaed43.js:21 Uncaught (in promise) Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at f.crossDomainError (main-da815c25abb660aaed43.js:21)
    at XMLHttpRequest.e.onreadystatechange (main-da815c25abb660aaed43.js:21)
    at XMLHttpRequest.<anonymous> (main-da815c25abb660aaed43.js:103)
    at XMLHttpRequest.n (main-da815c25abb660aaed43.js:103)
f.crossDomainError @ main-da815c25abb660aaed43.js:21
e.onreadystatechange @ main-da815c25abb660aaed43.js:21
(anonymous) @ main-da815c25abb660aaed43.js:103
n @ main-da815c25abb660aaed43.js:103
async function (async)
Cn @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
async function (async)
(anonymous) @ main-da815c25abb660aaed43.js:103
t @ main-da815c25abb660aaed43.js:35
(anonymous) @ main-da815c25abb660aaed43.js:103
(anonymous) @ main-da815c25abb660aaed43.js:103
Ca @ main-da815c25abb660aaed43.js:72
yg @ main-da815c25abb660aaed43.js:72
e.unstable_runWithPriority @ main-da815c25abb660aaed43.js:80
Ki @ main-da815c25abb660aaed43.js:72
pg @ main-da815c25abb660aaed43.js:72
rg @ main-da815c25abb660aaed43.js:72
(anonymous) @ main-da815c25abb660aaed43.js:72
e.unstable_runWithPriority @ main-da815c25abb660aaed43.js:80
Ki @ main-da815c25abb660aaed43.js:72
_i @ main-da815c25abb660aaed43.js:72
Wi @ main-da815c25abb660aaed43.js:72
ag @ main-da815c25abb660aaed43.js:72
_g @ main-da815c25abb660aaed43.js:72
render @ main-da815c25abb660aaed43.js:72
(anonymous) @ main-da815c25abb660aaed43.js:103
t @ main-da815c25abb660aaed43.js:1
(anonymous) @ main-da815c25abb660aaed43.js:1
(anonymous) @ main-da815c25abb660aaed43.js:1
main-da815c25abb660aaed43.js:103 POST https://o403236.ingest.sentry.io/api/5265532/store/?sentry_key=01d9c8f4220e4107992cfc3599c2f8e1&sentry_version=7 413 (Request Entity Too Large)
```

Any ideas on what could be going on? I'm happy to help debug more. Thanks!

**Comment by geekuillaume** [comment]
Hello Dustin, thanks for opening this issue. You're the first person that I don't personally know that interacted with this project :)
- The error `The AudioContext was not allowed to start` is expected. It is thrown because of a anti-spam protection from the browser that wait for the first interaction with the page (click for example) to start the AudioContext and allow the page to output audio. I didn't yet implemented a way of showing a message to ask the user to click on the page to start it. It's on the TODO list but will not impact the webaudio feature directly.
- `Access to XMLHttpRequest at 'https://soundsync.app/api/ip_registry/peers' from origin 'http://10.0.1.10:6512' has been blocked by CORS policy` is also expected when accessing the webui from the ip of one of the peer instead of the https://soundsync.app/. It shouldn't be a problem as the webui will try to connect to the peer directly and this peer will initiate the connection to all the other peers.
- `f60e6d23_541c_42d8_b464_198c26c0c930-192-168-239-1.sslip.io:6513/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED` seems to be caused by a problem I already encountered but is hardly fixable. This domain is a trick used to redirect to 192.168.239.1 but some DNS resolvers have rules to block every DNS entry to a LAN ip address. Can you try manually using this domain name with a `ping` to see what's being resolved?
- The crash when starting a audio source are something I also experienced. I've fixed it on Linux (which I use at home) but it's probably still broken on other OS. On MacOS, can you try starting the binary directly from the terminal to get a console output? You should only need to execute the binary with the command `/Applications/Soundsync.app/Contents/MacOS/Soundsync` (you'll need to adapt the path if you installed Soundsync at another location).

I need to implement a way to get output log from MacOS and Windows in case of a crash. I've added a Sentry integration but the last line in your logs explain why I haven't received any alert. I'm going to continue working on that.

**Comment by geekuillaume** [comment]
I've pushed a new version that should prevent some errors and add error reporting for connection errors. Can you try again @dustinkerstein ?

**Comment by dustinkerstein** [comment]
Hey! Thanks for getting back to me. Did you upload a new binary? I think I'm seeing the same 0.1.0 version.

> This domain is a trick used to redirect to 192.168.239.1 but some DNS resolvers have rules to block every DNS entry to a LAN ip address. Can you try manually using this domain name with a ping to see what's being resolved?

I am unable to ping 7d8f8749_3fad_4200_acf1_cc55e4ba51fe-10-0-1-10.sslip.io when the server is running, or any of these addresses:
![image](https://user-images.githubusercontent.com/7659306/85348949-0694d780-b4cb-11ea-9bc3-b934c360e74f.png)

When running the OSX server from the terminal I can't seem to get the https://soundsync.app webpage working. It just spins forever (with the errors above in Safari or related to CORS in Firefox. If I go to the local IP address I am able to get the microphone hooked up, but then it crashes. Here's the log:

 ```
soundsync Starting soundsync +0ms
  soundsync:wrtc Creating peer manager +0ms
  soundsync:config Reading config from /Users/dustin/Library/Preferences/soundsync/config.json +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Created new peer +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Registering local peer with instaceUuid: d01ed5c7-7439-4fc1-9f74-042583798877 +1ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'd01ed5c7-7439-4fc1-9f74-042583798877',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Connected +0ms
  soundsync:sourcesSinksManager Adding source MacBook Pro Microphone of type localdevice +0ms
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Created new audio source +0ms
  soundsync:sourcesSinksManager Adding sink  Z27 of type localdevice +2ms
  soundsync:audioSink:9db83aea-2dd6-47b5-ae9e-acb6bcb4147b Created new audio sink of type localdevice +0ms
  soundsync:sourcesSinksManager Adding sink  MacBook Pro Speakers of type localdevice +21ms
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Created new audio sink of type localdevice +0ms
  soundsync:sourcesSinksManager Detecting local audio devices +0ms
  soundsync:httpserver Creating new http server +0ms
  soundsync:httpserver Listening on 6512 +5ms
  soundsync:httpserver Creating https server on 6513 +0ms
  soundsync:rendezvous Registering to rendezvous service with: 10.0.1.147:6512,169.254.226.59:6512 +0ms
  soundsync:clientCoordinator Created client coordinator +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.10:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.226.59:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.226.59:6512 Cannot connect to peer with initiator http api Conflict +46ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.226.59:6512 Destroying peer, reason: Initiator hinted that it we should abort +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.226.59:6512 Cleaning webrtc state +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.226.59:6512 Connection closed, cause: controller channel is closed +6ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Cannot connect to peer with initiator http api Conflict +52ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Destroying peer, reason: Initiator hinted that it we should abort +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Cleaning webrtc state +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Connection closed, cause: controller channel is closed +3ms
  soundsync:peer:placeholderForHttpApiJoin_fe80::aede:48ff:fe00:1122:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_fe80::aede:48ff:fe00:1122:6512 Cannot connect to peer with initiator http api getaddrinfo ENOTFOUND fe80 +7ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.10:6512 Cannot connect to peer with initiator http api connect ETIMEDOUT 10.0.1.10:6512 +26s
  soundsync:peer:placeholderForHttpInitiatorRequest_d9e10e9e-1045-41bd-9d3d-e12f1c60c270 Created new peer +0ms
  soundsync:peer:placeholderForHttpInitiatorRequest_d9e10e9e-1045-41bd-9d3d-e12f1c60c270 Setting remote description +2ms
  soundsync:peer:placeholderForHttpInitiatorRequest_d9e10e9e-1045-41bd-9d3d-e12f1c60c270:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'd01ed5c7-7439-4fc1-9f74-042583798877',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForHttpInitiatorRequest_d9e10e9e-1045-41bd-9d3d-e12f1c60c270:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '820a32e5-1ccc-40ca-95c4-225b9b3dda36',
    name: 'Web page',
    instanceUuid: 'f6757393-72c5-49bb-a9b1-dc85141e9fc6',
    capacities: []
  }
} +0ms
  soundsync:peer:820a32e5-1ccc-40ca-95c4-225b9b3dda36 Connected +0ms
  soundsync:sourcesSinksManager Adding sink  Web Page Output of type webaudio +4m
  soundsync:audioSink:d211f605-0edb-4eee-9a7f-1519671d39f8 Created new audio sink of type webaudio +0ms
  soundsync:peer:820a32e5-1ccc-40ca-95c4-225b9b3dda36 Updating timedelta to -227641.36968450248, diff was -227641.37ms +67ms
  soundsync:peer:820a32e5-1ccc-40ca-95c4-225b9b3dda36 Updating timedelta to -227661.9834436234, diff was -20.61ms +10s
  soundsync:peer:820a32e5-1ccc-40ca-95c4-225b9b3dda36 Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +34s
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Starting audio source +5m
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Creating localdevice sink +1ms
libc++abi.dylib: terminating with uncaught exception of type Napi::Error: Cannot read property '0' of undefined
Abort trap: 6
```

Let me know how else I can help.

**Comment by geekuillaume** [comment]
Thanks for helping me with this :) I'm not yet increasing the version number at each build as almost nobody is using this project for now. Once the official beta starts, I'll start increasing the version number for each release.

It seems that your DNS is blocking this entry to a local IP address. To be sure it's because of the DNS, can you use the Network Utility in MacOS to do a lookup of this domain `7d8f8749_3fad_4200_acf1_cc55e4ba51fe-10-0-1-10.sslip.io`? It should return the ip `10.0.1.10` like this:
![image](https://user-images.githubusercontent.com/1301701/85382544-5d3bf900-b53f-11ea-8fbd-ef67f736efae.png)

If you get something else, can you try switching to another DNS server like `1.1.1.1` for Cloudflare or `8.8.8.8` for Google which are working with this domain?

The error seems to be related to your microphone being mono but Soundsync trying to access the second (not existing) channel of the audio stream. MacOS sound API is tricky to debug but I've pushed a fix that should help. Can you try again @dustinkerstein ?

Thanks again!

**Comment by dustinkerstein** [comment]
Interesting. If I manually set my DNS in OSX to 8.8.8.8 I can resolve that address, but if I use my router (DD-WRT) provided DNS (which was already statically set to 8.8.8.8 and 8.8.4.4) it doesn't work. Now the https://soundsync.app loads which is good, but I still appear to get some SSL errors:

```
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (cf0dd422_d5c5_441b_a38a_5d8305844a51-169-254-97-71.sslip.io, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (b8138e0e_8cc4_4c65_9b7c_d300a5e18d86-10-0-1-147.sslip.io, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (cf0dd422_d5c5_441b_a38a_5d8305844a51-169-254-97-71.sslip.io, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (b8138e0e_8cc4_4c65_9b7c_d300a5e18d86-10-0-1-147.sslip.io, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (cf0dd422_d5c5_441b_a38a_5d8305844a51-169-254-97-71.sslip.io, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (b8138e0e_8cc4_4c65_9b7c_d300a5e18d86-10-0-1-147.sslip.io, line 0)
```

With the latest code I seem to be able to link my mic input to the speaker output and hear audio (the expected echo). But hooking it up to the web page output doesn't produce any sound. Maybe I'm not understanding something about the webpage output. Is there a separate "listen only" webpage that doesn't allow you to manage the sources/sinks?

Also, here's the debug from switching between webpage output and speaker output.

```
soundsync Starting soundsync +0ms
  soundsync:wrtc Creating peer manager +0ms
  soundsync:config Reading config from /Users/dustin/Library/Preferences/soundsync/config.json +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Created new peer +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Registering local peer with instaceUuid: fc1e1185-7420-43e0-bde3-8e35fc9607f5 +1ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'fc1e1185-7420-43e0-bde3-8e35fc9607f5',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Connected +0ms
  soundsync:sourcesSinksManager Adding source MacBook Pro Microphone of type localdevice +0ms
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Created new audio source +0ms
  soundsync:sourcesSinksManager Adding sink  Z27 of type localdevice +2ms
  soundsync:audioSink:9db83aea-2dd6-47b5-ae9e-acb6bcb4147b Created new audio sink of type localdevice +0ms
  soundsync:sourcesSinksManager Adding sink  MacBook Pro Speakers of type localdevice +21ms
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Created new audio sink of type localdevice +0ms
  soundsync:sourcesSinksManager Detecting local audio devices +1ms
  soundsync:httpserver Creating new http server +0ms
  soundsync:httpserver Listening on 6512 +5ms
  soundsync:httpserver Creating https server on 6513 +0ms
  soundsync:rendezvous Registering to rendezvous service with: 169.254.97.71:6512,10.0.1.147:6512 +0ms
  soundsync:clientCoordinator Created client coordinator +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.97.71:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.97.71:6512 Cannot connect to peer with initiator http api Conflict +28ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.97.71:6512 Destroying peer, reason: Initiator hinted that it we should abort +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.97.71:6512 Cleaning webrtc state +0ms
  soundsync:peer:placeholderForHttpApiJoin_169.254.97.71:6512 Connection closed, cause: controller channel is closed +7ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Cannot connect to peer with initiator http api Conflict +39ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Destroying peer, reason: Initiator hinted that it we should abort +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Cleaning webrtc state +1ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Connection closed, cause: controller channel is closed +2ms
  soundsync:peer:placeholderForHttpApiJoin_fe80::aede:48ff:fe00:1122:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_fe80::aede:48ff:fe00:1122:6512 Cannot connect to peer with initiator http api getaddrinfo ENOTFOUND fe80 +10ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_111682d9-4375-4243-b284-df1e9af13fbc Created new peer +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_111682d9-4375-4243-b284-df1e9af13fbc Setting remote description +1ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_06beb825-6177-422d-b86d-ff8fa5c4b394 Created new peer +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_06beb825-6177-422d-b86d-ff8fa5c4b394 Setting remote description +2ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_111682d9-4375-4243-b284-df1e9af13fbc:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'fc1e1185-7420-43e0-bde3-8e35fc9607f5',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_111682d9-4375-4243-b284-df1e9af13fbc:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '2319da23-bc41-4085-9a9b-f3dd9c0d1798',
    name: 'Web page',
    instanceUuid: '1cde2c5a-8585-4825-bf23-ec455832aa5a',
    capacities: []
  }
} +0ms
  soundsync:peer:2319da23-bc41-4085-9a9b-f3dd9c0d1798 Connected +0ms
  soundsync:sourcesSinksManager Adding sink  Web Page Output of type webaudio +6s
  soundsync:audioSink:f2c23381-5abe-4849-8d6e-8c8881e2e087 Created new audio sink of type webaudio +0ms
  soundsync:peer:2319da23-bc41-4085-9a9b-f3dd9c0d1798 Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +33ms
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Starting audio source +6s
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Creating localdevice source +1ms
  soundsync:peer:2319da23-bc41-4085-9a9b-f3dd9c0d1798 Updating timedelta to -4420.243312999606, diff was -4420.24ms +20ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_06beb825-6177-422d-b86d-ff8fa5c4b394:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'fc1e1185-7420-43e0-bde3-8e35fc9607f5',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_06beb825-6177-422d-b86d-ff8fa5c4b394:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '2319da23-bc41-4085-9a9b-f3dd9c0d1798',
    name: 'Web page',
    instanceUuid: '1cde2c5a-8585-4825-bf23-ec455832aa5a',
    capacities: []
  }
} +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_06beb825-6177-422d-b86d-ff8fa5c4b394 Destroying peer, reason: Peer is already connected, this is a duplicate +901ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_06beb825-6177-422d-b86d-ff8fa5c4b394 Cleaning webrtc state +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_06beb825-6177-422d-b86d-ff8fa5c4b394 Connection closed, cause: controller channel is closed +3ms
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:peer:2319da23-bc41-4085-9a9b-f3dd9c0d1798:sinkPatch Received controller message {
  type: 'sinkPatch',
  sink: {
    uuid: 'bb990eff-0850-4482-949e-e73daab19ee2',
    instanceUuid: '9567090e-53fd-496a-97fd-5a7bc54f09d6',
    pipedFrom: '87acf534-18d1-43fe-9aa5-472e7384a939'
  }
} +0ms
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Linking audio source MacBook Pro Microphone (uuid 87acf534-18d1-43fe-9aa5-472e7384a939) to sink +50s
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Creating speaker +2ms
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Resync because of audio clock skew: -50.833333333333336ms +5s
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Resync because of audio clock skew: -50.041666666666664ms +5s
  soundsync:peer:2319da23-bc41-4085-9a9b-f3dd9c0d1798:sinkPatch Received controller message {
  type: 'sinkPatch',
  sink: {
    uuid: 'bb990eff-0850-4482-949e-e73daab19ee2',
    instanceUuid: '9567090e-53fd-496a-97fd-5a7bc54f09d6',
    pipedFrom: null
  }
} +14s
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Source stream has closed, unlinking +4s
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:peer:2319da23-bc41-4085-9a9b-f3dd9c0d1798 Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +1m
  soundsync:peer:2319da23-bc41-4085-9a9b-f3dd9c0d1798:sinkPatch Received controller message {
  type: 'sinkPatch',
  sink: {
    uuid: 'bb990eff-0850-4482-949e-e73daab19ee2',
    instanceUuid: '9567090e-53fd-496a-97fd-5a7bc54f09d6',
    pipedFrom: '87acf534-18d1-43fe-9aa5-472e7384a939'
  }
} +1m
```

**Comment by geekuillaume** [comment]
Good news :) It seems like the dns resolver of OpenWRT prevent DNS rebinding by default (https://openwrt.org/docs/guide-user/base-system/dhcp) but this is necessary to connect to local IP addresses from an external page. This is also why I use this "SSL hack" with this weird domain name and why there are SSL errors (as the server doesn't have any valid certificate). These errors are expected as we only need the first SSL handshake to advertise the connection uuid to the other peer (the uuid being the first part of the domain name).

The webpage should output audio when connecting. Can you send me the console output of the webpage? Which browser are you using? I only tested with Chrome and Firefox for now.

**Comment by geekuillaume** [comment]
Also @dustinkerstein you can contact me at guillaume+soundsync@besson.co to discuss in private a commercial use of Soundsync

**Comment by dustinkerstein** [comment]
I was able to get mic audio working in Firefox on OSX. Safari didn't have any useful debug beyond the SSL errors, and Chrome seems to require that user action before allowing audio to play. Here's the full server log during testing several browsers (some working and some non working attempts).

  ```
soundsync Starting soundsync +0ms
  soundsync:wrtc Creating peer manager +0ms
  soundsync:config Reading config from /Users/dustin/Library/Preferences/soundsync/config.json +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Created new peer +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Registering local peer with instaceUuid: e1dee9e5-9b64-4d01-aa95-167fe5573250 +1ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'e1dee9e5-9b64-4d01-aa95-167fe5573250',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:9620bf04-441b-4829-b068-6893e8cc2699 Connected +0ms
  soundsync:sourcesSinksManager Adding source MacBook Pro Microphone of type localdevice +0ms
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Created new audio source +0ms
  soundsync:sourcesSinksManager Adding sink  Z27 of type localdevice +2ms
  soundsync:audioSink:9db83aea-2dd6-47b5-ae9e-acb6bcb4147b Created new audio sink of type localdevice +0ms
  soundsync:sourcesSinksManager Adding sink  MacBook Pro Speakers of type localdevice +20ms
  soundsync:audioSink:bb990eff-0850-4482-949e-e73daab19ee2 Created new audio sink of type localdevice +0ms
  soundsync:sourcesSinksManager Detecting local audio devices +1ms
  soundsync:httpserver Creating new http server +0ms
  soundsync:httpserver Listening on 6512 +5ms
  soundsync:httpserver Creating https server on 6513 +0ms
  soundsync:rendezvous Registering to rendezvous service with: 10.0.1.147:6512 +0ms
  soundsync:clientCoordinator Created client coordinator +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Cannot connect to peer with initiator http api Conflict +28ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Destroying peer, reason: Initiator hinted that it we should abort +0ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Cleaning webrtc state +1ms
  soundsync:peer:placeholderForHttpApiJoin_10.0.1.147:6512 Connection closed, cause: controller channel is closed +3ms
  soundsync:peer:placeholderForHttpInitiatorRequest_55e3ccb9-f79a-48da-9081-7e8f01e1491b Created new peer +0ms
  soundsync:peer:placeholderForHttpInitiatorRequest_55e3ccb9-f79a-48da-9081-7e8f01e1491b Setting remote description +2ms
  soundsync:peer:placeholderForHttpInitiatorRequest_55e3ccb9-f79a-48da-9081-7e8f01e1491b:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'e1dee9e5-9b64-4d01-aa95-167fe5573250',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForHttpInitiatorRequest_55e3ccb9-f79a-48da-9081-7e8f01e1491b:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '65a1c86a-a14a-4582-a4fb-c2f383d7abda',
    name: 'Web page',
    instanceUuid: '4be9583e-3f07-4035-ad6e-2de0c5e35131',
    capacities: []
  }
} +0ms
  soundsync:peer:65a1c86a-a14a-4582-a4fb-c2f383d7abda Connected +0ms
  soundsync:sourcesSinksManager Adding sink  Web Page Output of type webaudio +3s
  soundsync:audioSink:d211f605-0edb-4eee-9a7f-1519671d39f8 Created new audio sink of type webaudio +0ms
  soundsync:peer:65a1c86a-a14a-4582-a4fb-c2f383d7abda Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +2ms
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Starting audio source +3s
  soundsync:audioSource:87acf534-18d1-43fe-9aa5-472e7384a939 Creating localdevice source +1ms
  soundsync:peer:65a1c86a-a14a-4582-a4fb-c2f383d7abda Updating timedelta to 39342.363239496946, diff was 39342.36ms +74ms
  soundsync:peer:65a1c86a-a14a-4582-a4fb-c2f383d7abda Updating timedelta to 39363.882580492646, diff was 21.52ms +8ms
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:peer:placeholderForHttpApiJoin_fe80::aede:48ff:fe00:1122:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_fe80::aede:48ff:fe00:1122:6512 Cannot connect to peer with initiator http api getaddrinfo ENOTFOUND fe80 +7ms
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:peer:65a1c86a-a14a-4582-a4fb-c2f383d7abda Connection closed, cause: controller channel is closed +9s
  soundsync:peer:65a1c86a-a14a-4582-a4fb-c2f383d7abda Cleaning webrtc state +0ms
  soundsync:peer:placeholderForHttpInitiatorRequest_b224549a-e86d-4758-92da-339c6e8247c1 Created new peer +0ms
  soundsync:peer:placeholderForHttpInitiatorRequest_b224549a-e86d-4758-92da-339c6e8247c1 Setting remote description +1ms
  soundsync:peer:placeholderForHttpInitiatorRequest_b224549a-e86d-4758-92da-339c6e8247c1:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'e1dee9e5-9b64-4d01-aa95-167fe5573250',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForHttpInitiatorRequest_b224549a-e86d-4758-92da-339c6e8247c1:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: 'e6ba5df9-bde6-4355-b985-bed53a059da9',
    name: 'Web page',
    instanceUuid: 'aa8cc5a5-a014-462c-b051-5ba5ae4a60f2',
    capacities: []
  }
} +0ms
  soundsync:peer:e6ba5df9-bde6-4355-b985-bed53a059da9 Connected +0ms
  soundsync:peer:e6ba5df9-bde6-4355-b985-bed53a059da9 Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +50ms
  soundsync:peer:e6ba5df9-bde6-4355-b985-bed53a059da9 Updating timedelta to -12076.838569507003, diff was -12076.84ms +0ms
  soundsync:peer:e6ba5df9-bde6-4355-b985-bed53a059da9 Updating timedelta to -12049.930091507733, diff was 26.91ms +35ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e0ad6505-efcb-4995-b9bc-415f91d82d87 Created new peer +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e0ad6505-efcb-4995-b9bc-415f91d82d87 Setting remote description +1ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e0ad6505-efcb-4995-b9bc-415f91d82d87:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'e1dee9e5-9b64-4d01-aa95-167fe5573250',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e0ad6505-efcb-4995-b9bc-415f91d82d87:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: 'e6ba5df9-bde6-4355-b985-bed53a059da9',
    name: 'Web page',
    instanceUuid: 'aa8cc5a5-a014-462c-b051-5ba5ae4a60f2',
    capacities: []
  }
} +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e0ad6505-efcb-4995-b9bc-415f91d82d87 Destroying peer, reason: Peer is already connected, this is a duplicate +886ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e0ad6505-efcb-4995-b9bc-415f91d82d87 Cleaning webrtc state +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e0ad6505-efcb-4995-b9bc-415f91d82d87 Connection closed, cause: controller channel is closed +2ms
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:peer:e6ba5df9-bde6-4355-b985-bed53a059da9 Connection closed, cause: controller channel is closed +22s
  soundsync:peer:e6ba5df9-bde6-4355-b985-bed53a059da9 Cleaning webrtc state +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_2d564151-288a-41ae-afca-570f4a385524 Created new peer +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_2d564151-288a-41ae-afca-570f4a385524 Setting remote description +1ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_2d564151-288a-41ae-afca-570f4a385524:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'e1dee9e5-9b64-4d01-aa95-167fe5573250',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_2d564151-288a-41ae-afca-570f4a385524:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: 'e83361ec-f744-466b-bd6f-ac0ef7c19fc2',
    name: 'Web page',
    instanceUuid: '6cf0961c-68c7-4bfe-ba73-5cbec1006d27',
    capacities: []
  }
} +0ms
  soundsync:peer:e83361ec-f744-466b-bd6f-ac0ef7c19fc2 Connected +0ms
  soundsync:sourcesSinksManager Adding sink  Web Page Output of type webaudio +33s
  soundsync:audioSink:f2c23381-5abe-4849-8d6e-8c8881e2e087 Created new audio sink of type webaudio +0ms
  soundsync:peer:e83361ec-f744-466b-bd6f-ac0ef7c19fc2 Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +48ms
  soundsync:peer:e83361ec-f744-466b-bd6f-ac0ef7c19fc2 Updating timedelta to -33892.6591405049, diff was -33892.66ms +1ms
  soundsync:peer:e83361ec-f744-466b-bd6f-ac0ef7c19fc2 Updating timedelta to -33868.840891007334, diff was 23.82ms +22ms
Stream out of data, stopping reading loop until new data arrives
Stream started again
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e21a37c9-e641-4e5f-b249-27831d8e800b Created new peer +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e21a37c9-e641-4e5f-b249-27831d8e800b Received candidate but connection was not yet initialized, ignoring +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e21a37c9-e641-4e5f-b249-27831d8e800b Setting remote description +1ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e21a37c9-e641-4e5f-b249-27831d8e800b:peerInfo Sending controller message {
  type: 'peerInfo',
  peer: {
    uuid: '9620bf04-441b-4829-b068-6893e8cc2699',
    name: 'dustin.cable.rcn.com',
    instanceUuid: 'e1dee9e5-9b64-4d01-aa95-167fe5573250',
    capacities: [ 'librespot', 'shairport', 'http_server_accessible', 'hue' ]
  }
} +0ms
  soundsync:peer:placeholderForRendezvousInitiatorRequest_e21a37c9-e641-4e5f-b249-27831d8e800b:peerInfo Received controller message {
  type: 'peerInfo',
  peer: {
    uuid: '82691774-0af2-43c1-809e-03e58572f08f',
    name: 'Web page',
    instanceUuid: '15622f92-0cff-47e2-8c52-e7e5da4e851f',
    capacities: []
  }
} +0ms
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Connected +0ms
  soundsync:sourcesSinksManager Adding sink  Web Page Output of type webaudio +37s
  soundsync:audioSink:bb7feb17-ea07-4739-acfa-ffc22258b588 Created new audio sink of type webaudio +0ms
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Updating timedelta to -70633.86986400932, diff was -70633.87ms +38ms
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +12s
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Connection closed, cause: no heartbeat received +24s
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Cleaning webrtc state +0ms
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Cannot connect to peer with initiator rendezvous service This method is meant to be used in a web context, not in a NodeJS one +2s
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Destroying peer, reason: Initiator hinted that it we should abort +1ms
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Cleaning webrtc state +0ms
  soundsync:peer:82691774-0af2-43c1-809e-03e58572f08f Connection closed, cause: controller channel is closed +1ms
  soundsync:peer:e83361ec-f744-466b-bd6f-ac0ef7c19fc2 Received request for source 87acf534-18d1-43fe-9aa5-472e7384a939 +1m
```

**Comment by dustinkerstein** [comment]
And a small (maybe large) feature suggestion for the browser output. It would be awesome to have the ability to output not just to "this current browser" but to a server hosted page that acts solely as a "list only" client with no other controls beyond volume. And further, to have multiple clients be able to connect to that same page and play in sync... That's essentially what I'll be emailing you about :)

**Comment by geekuillaume** [comment]
Thanks for the log. Because of the missing [AudioWorklet implementation in Safari](https://caniuse.com/#feat=mdn-api_audioworklet), the current way of handling audio doesn't work with Safari. I've added a detection code to prevent showing the sink when the browser isn't supported. 

It seems there is not other issues left. I'm closing this. Thanks again !
