### ISSUE TITLE
AirPlay from phone to laptop stutters

### ISSUE THREAD

**Issue by rosh324** [geekuillaume/soundsync#4]
I gave the software a test run by seeing if i could airplay from my phone to my headphones through my laptop and I experienced some stuttering in the middle like a CD that had a quick scratch. This may be related to the really high latency play/pause and volume controls had.

The setup was iPhone -> MacBook Pro through AirPlay.

**Comment by geekuillaume** [comment]
@rosh324 I've updated the code related to the audio synchronization to reduce audio glitches. Can you download Soundsync again and try?

**Comment by rosh324** [comment]
@geekuillaume How do I build the program? I assume the "download development version" link doesn't link to the latest commit.

**Comment by geekuillaume** [comment]
@rosh324 I configured Github to build the new development version every time I push a commit. The version number doesn't change but the downloadable binary contains the latest code. You just have to download and install it again.

**Comment by rosh324** [comment]
I gave it a try, the issue is definitely much better, the frequency of interruptions is lower and the interruptions themselves are much less noticeable. I do still get at least one per song though.

**Comment by geekuillaume** [comment]
Okay, thanks. I'm still working on it to get something perfect!

**Comment by geekuillaume** [comment]
@rosh324 can you try again? I improved the behavior when an audio chunk was received out-of-order (which can happen because of the WebRTC DataChannel mode I'm using)

**Comment by rosh324** [comment]
@geekuillaume Playback is now smooth, but there are some popping artifacts in the audio. I can't test on actual speakers but its definitely noticeable on headphones. It's probably something small in the reassembly. If I'm not mistaken you are converting the audio chunks to a different format that is more universal before pushing to the devices right? Could it have something to do with that process? I'm just speculating, I don't have much knowledge about streaming media in real time.

**Comment by geekuillaume** [comment]
@rosh324 I've again improved the whole audio packaging / playback logic to reduce the latency and improve the popping sounds. I've fixed several bugs and I don't hear anything wrong now. Can you download the last build of Soundsync and try again to see if this works well with your setup? Thanks :)

**Comment by rosh324** [comment]
@geekuillaume I am having a hard time testing because the menu bar icon to open the controller wont show up. I tried the external soundsync.app website as well and it couldnt find it.

**Comment by geekuillaume** [comment]
@rosh324 I've changed a lot of stuff recently and fixed also a lot of bugs. Can you try again with the last version (v0.2.4)?

**Comment by geekuillaume** [comment]
No response, I'm closing this. Feel free to reopen if you still experience this issue.

**Comment by Roshinator** [comment]
Hey its been a while, I just tried the latest version as of writing, 0.4.13 and wow it's a lot better. I'm definitely gonna flash this on a pi and repurpose some old speakers sometime. I played a few songs and I don't think I heard a single stutter. Keep up the good work :-).
